version: "3"

services:
  mysql:
    image: library/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=p4SSW0rd
        - MYSQL_DATABASE=courses
        - MYSQL_USER=Courses
        - MYSQL_PASSWORD=Courses
    ports:
        - "3306:3306"
    volumes:
        - backups:/docker-entrypoint-initdb.d
  app:
   image: openjdk:8u131-jre-alpine
   ports:
    - "8080:8080"  
   depends_on:
     - mysql
   working_dir: /appli
   volumes:
    - ./target/server-bd-1.0.jar:/appli/server-bd-1.0.jar
   command: java -jar /appli/server-bd-1.0.jar
   environment:
     - spring.datasource.url=jdbc:mysql://mysql:3306/courses?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     - spring.datasource.username=Courses
     - spring.datasource.password=Courses
volumes:
  backups:
